import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import { AIDisclosure } from "@/components/ui/AIDisclosure";

describe("AIDisclosure", () => {
  it("inline variant renders correct text", () => {
    render(<AIDisclosure variant="inline" />);
    expect(screen.getByText("AI-generated")).toBeInTheDocument();
  });

  it("badge variant renders AI with icon", () => {
    render(<AIDisclosure variant="badge" />);
    expect(screen.getByText("AI")).toBeInTheDocument();
  });

  it("badge has accessible description", () => {
    render(<AIDisclosure variant="badge" />);
    const badge = screen.getByText("AI").closest("span");
    expect(badge).toHaveAttribute("aria-describedby", "ai-disclosure-tooltip");
    expect(
      screen.getByText(
        "This content was generated by artificial intelligence",
      ),
    ).toBeInTheDocument();
  });

  it("section variant renders warning banner", () => {
    render(<AIDisclosure variant="section" />);
    const section = screen.getByRole("note");
    expect(section).toHaveTextContent(
      "This section is generated by AI. It may contain errors.",
    );
  });
});
