import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";

// Import the page component (named export)
import { TransparencyPage } from "@/app/transparency/page";

describe("Transparency page", () => {
  it("renders the main heading", () => {
    render(<TransparencyPage />);
    expect(
      screen.getByRole("heading", { level: 1, name: /AI Transparency/i }),
    ).toBeInTheDocument();
  });

  it("contains all 7 required sections", () => {
    render(<TransparencyPage />);
    const expectedSections = [
      "AI Systems We Use",
      "How AI Affects Your Results",
      "AI Disclosure Labels",
      "Data Sources",
      "Decision Logging",
      "Human Oversight",
      "Contact & Feedback",
    ];
    for (const section of expectedSections) {
      expect(
        screen.getByRole("heading", { name: new RegExp(section, "i") }),
      ).toBeInTheDocument();
    }
  });

  it("renders AIDisclosure examples in section 3", () => {
    render(<TransparencyPage />);
    // inline variant
    expect(screen.getByText("AI-generated")).toBeInTheDocument();
    // badge variant
    expect(screen.getByText("AI")).toBeInTheDocument();
    // section variant
    expect(
      screen.getByText(/This section is generated by AI/),
    ).toBeInTheDocument();
  });

  it("has ISR revalidate = 86400", async () => {
    const mod = await import("@/app/transparency/page");
    expect((mod as Record<string, unknown>).revalidate).toBe(86400);
  });
});
