import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";

// Import the page component (named export)
import { TransparencyPage } from "@/app/transparency/page";

describe("Transparency page", () => {
  it("renders the main heading", () => {
    render(<TransparencyPage />);
    expect(
      screen.getByRole("heading", { level: 1, name: /AI Transparency/i }),
    ).toBeInTheDocument();
  });

  it("contains all 7 required sections per SPEC §9.4", () => {
    render(<TransparencyPage />);
    const expectedSections = [
      "How AI Powers AtoZ Jobs",
      "Models Used",
      "What AI Decides",
      "What AI Does NOT Decide",
      "Known Limitations",
      "How to Contest",
      "Last Updated",
    ];
    for (const section of expectedSections) {
      expect(
        screen.getByRole("heading", { name: new RegExp(section, "i") }),
      ).toBeInTheDocument();
    }
  });

  it("renders AIDisclosure examples in section 1", () => {
    render(<TransparencyPage />);
    // inline variant
    expect(screen.getByText("AI-generated")).toBeInTheDocument();
    // badge variant
    expect(screen.getByText("AI")).toBeInTheDocument();
    // section variant
    expect(
      screen.getByText(/This section is generated by AI/),
    ).toBeInTheDocument();
  });

  it("has ISR revalidate = 86400", async () => {
    const mod = await import("@/app/transparency/page");
    expect((mod as Record<string, unknown>).revalidate).toBe(86400);
  });

  it("lists specific model names", () => {
    render(<TransparencyPage />);
    expect(screen.getByText(/Gemini embedding-001/)).toBeInTheDocument();
    expect(screen.getByText(/ms-marco-MiniLM-L-6-v2/)).toBeInTheDocument();
    expect(screen.getByText(/GPT-4o-mini/)).toBeInTheDocument();
    expect(screen.getByText(/XGBoost/)).toBeInTheDocument();
  });

  it("mentions salary prediction MAE", () => {
    render(<TransparencyPage />);
    expect(screen.getByText(/±£5,000–£8,000/)).toBeInTheDocument();
  });
});
