interface AIDisclosureProps {
  variant: "inline" | "badge" | "section";
}

export function AIDisclosure({ variant }: AIDisclosureProps) {
  switch (variant) {
    case "inline":
      return (
        <span className="text-xs text-gray-500">
          AI-generated
        </span>
      );

    case "badge":
      return (
        <span
          className="inline-flex items-center gap-1 rounded-full bg-blue-100 px-2 py-0.5 text-xs font-medium text-blue-700"
          aria-describedby="ai-disclosure-tooltip"
        >
          <svg
            className="h-3 w-3"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M13 10V3L4 14h7v7l9-11h-7z"
            />
          </svg>
          AI
          <span id="ai-disclosure-tooltip" className="sr-only">
            This content was generated by artificial intelligence
          </span>
        </span>
      );

    case "section":
      return (
        <div
          className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"
          role="note"
        >
          This section is generated by AI. It may contain errors.
        </div>
      );
  }
}
