-- Rollback Migration 017: Revoke pgmq schema permissions from service_role

ALTER DEFAULT PRIVILEGES IN SCHEMA pgmq
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgmq
    REVOKE EXECUTE ON FUNCTIONS FROM service_role;

REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA pgmq FROM service_role;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA pgmq FROM service_role;
REVOKE USAGE ON SCHEMA pgmq FROM service_role;
